-- Syntax
hl("Comment", { fg = C.gray, italic = true })
hl("Constant", { fg = C.acc })
hl("String", { fg = C.pink })
hl("Character", { fg = C.pink })
hl("Number", { fg = C.pink })
hl("Boolean", { fg = C.acc, bold = true })
hl("Float", { fg = C.pink })
hl("Identifier", { fg = C.purple })
hl("Function", { fg = C.purple })
hl("Statement", { fg = C.acc })
hl("Conditional", { fg = C.acc })
hl("Repeat", { fg = C.acc })
hl("Label", { fg = C.acc })
hl("Operator", { fg = C.purple })
hl("Keyword", { fg = C.acc })
hl("Exception", { fg = C.acc })
hl("PreProc", { fg = C.red })
hl("Include", { fg = C.acc })
hl("Define", { fg = C.acc })
hl("Macro", { fg = C.red })
hl("PreCondit", { fg = C.red })
hl("Type", { fg = C.blue })
hl("StorageClass", { fg = C.acc })
hl("Structure", { fg = C.blue })
hl("Typedef", { fg = C.blue })
hl("Special", { fg = C.red })
hl("SpecialChar", { fg = C.acc })
hl("Tag", { fg = C.acc })
hl("Delimiter", { fg = C.gray })
hl("SpecialComment", { fg = C.gray, italic = true })
hl("Debug", { fg = C.red })
hl("Underlined", { fg = C.pink, underline = true })
hl("Ignore", { fg = C.gray })
hl("Error", { fg = C.red, bg = C.bg })
hl("Todo", { fg = C.bg, bg = C.pink, bold = true })
