## Cava configuration — Right channel only
[general]
bars = 15
autosens = 1
sensitivity = 100
sleep_timer = 5

[input]
method = pulse
source = auto

[output]
method = raw
data_format = ascii
ascii_max_range = 8
bar_delimiter = 32
raw_target = /dev/stdout
channels = mono
mono_option = right

[color]
gradient = 0

[smoothing]
noise_reduction = 77
monstercat = 0
waves = 0
